luca652/motorino

Gemfile, Gemfile.lock, app/controllers/pages_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/pages/index.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230513152027_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
added 'devise' gem
created 'user' model
=> Set up Devise authentication

app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb
Added _flashes.html.erb partial following lecture template
=> added devise flashes partial

app/models/booking.rb, app/models/moped.rb, app/models/user.rb, db/migrate/20230515100230_create_mopeds.rb, db/migrate/20230515100839_create_bookings.rb, db/schema.rb, test/models/booking_test.rb, test/models/moped_test.rb
had to name model "moped" rather than "motorino" as agreed because Rails won't let you use the app's name as model name. 
this means our controller will have to be called "mopeds controller" and our routes will change. I am happy to update routes.
=> added moped and booking models and sorted relationships

app/controllers/bookings_controller.rb, app/controllers/mopeds_controller.rb, app/models/booking.rb, app/models/moped.rb, app/models/user.rb, app/views/bookings/my_bookings.html.erb, app/views/mopeds/index.html.erb, app/views/mopeds/show.html.erb, config/routes.rb, db/migrate/20230515195114_add_columns_to_user.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/controllers/mopeds_controller_test.rb
I have added validations and crash tested the models. It all seems to be working. I have added routes for all the pages discussed on Saturday. I have also added mopeds controller and bookings controller. Let me know what you think!
=> Validations

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
Hi guys, I have been working on the layout of the home page. 
I have modified and improved the nav-bar, highlighting the button sign-in and log-in. I have modified the drop-down menu with the help and the language options. I still have an issue with how to space the button correctly, so feedbacks are welcome.
I have created the footer and added a banner to the home page. At the moment the banner is carrying the calendar button.
=> added footer, improved nav-bar, added banner to home page

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, app/views/shared/_navbar.html.erb
Updated forms in devise views with first and last name fields.
=> Authenticate

app/controllers/application_controller.rb, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, app/views/shared/_navbar.html.erb
Fixed sign out function - we can now sign up, sign in and sign out! Rejoice. 
Vittoria, I realised I had to include an if statement in the navbar in order to make that work, so I had to change bits of your code (I followed the template for the navbar in the Devise lecture). Please have a look before you merge.
=> added sign out functionality - we can now sign up, log in and sign out

Gemfile, Gemfile.lock, app/controllers/bookings_controller.rb, db/seeds.rb
I added seeds to populate db with users, mopeds and bookings.
=> added seeds to populate db

app/views/pages/index.html.erb
I have correct link_to show page. This should work.
=> set up index page with link to show page

app/assets/stylesheets/pages/_home.scss, app/controllers/mopeds_controller.rb, app/views/pages/index.html.erb
I have tried to improve the visual of the moped card. Improvements are still needed as I can't work out how to fix the spacing.
=> adjasted card view in idex

app/controllers/bookings_controller.rb, app/models/user.rb, app/views/bookings/my_bookings.html.erb
Added dependent destroy to User model. Now if we destroy a user all the user's scooters will be destroyed too.
=> Edit validations

Gemfile, Gemfile.lock, app/controllers/mopeds_controller.rb, app/views/mopeds/edit.html.erb, app/views/mopeds/index.html.erb, app/views/mopeds/show.html.erb, db/migrate/20230515100839_create_bookings.rb
i added the edit and delete buttons
=> new-feature update and delete buttons

app/controllers/bookings_controller.rb, app/controllers/mopeds_controller.rb, app/views/bookings/new.html.erb, app/views/mopeds/show.html.erb, config/routes.rb
=> added booking form on show page and create method in bookings controller

app/controllers/bookings_controller.rb, app/controllers/mopeds_controller.rb, app/views/bookings/my_bookings.html.erb, app/views/mopeds/my_mopeds.html.erb, app/views/shared/_my_booking.html.erb, config/routes.rb, db/migrate/20230519151419_add_confirmed_to_booking.rb, db/schema.rb, db/seeds.rb
I have created a new route (get :confirmed), a new action in the bookings controller (confirmed), and tweaked the my_mopeds view. 
Now when a booking request is created by a user, the owner of that scooter will see a link on the moped's card that says "Confirm booking". By clicking on the link, the owner accepts the booking (and the field 'confirmed' in the bookings table gets switched from false to true).
=> Booking confirmation

app/views/bookings/my_bookings.html.erb, app/views/mopeds/my_mopeds.html.erb, app/views/mopeds/show.html.erb
Removed link to local file which was throwing up error in heroku
=> deleted link to '.jpg' file from views

app/views/bookings/my_bookings.html.erb, app/views/pages/index.html.erb
removed button from cards on index
added "confirmed bookings" section to "my bookings" page. Added "Pending" tag to unconfirmed booking.
=> removed button from cards

app/javascript/application.js, app/javascript/controllers/datepicker_controller.js, app/javascript/controllers/index.js, app/views/mopeds/show.html.erb
I have fixed the problem with the datepicker by creating a DatepickerController.js. Now the user should be able to input the dates through a calendar without refreshing the page.
=> added a DatapickerController.js

app/assets/stylesheets/components/_footer.scss, app/views/mopeds/show.html.erb
Hi guys, I have fixed the footer by modifying the css of the body. 
Also, I have reconnected the DatapickerController to simple_form in show.html.
=> Merge fixes

app/assets/stylesheets/pages/_show.scss, app/views/mopeds/show.html.erb, db/schema.rb
i made updates to the show page
=> Show page2

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_marker.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_moped_index.scss, app/javascript/controllers/map_controller.js, app/views/mopeds/_info_window.html.erb, app/views/mopeds/_marker.html.erb, app/views/mopeds/index.html.erb
I have created an anchor between the popups windows and the cards.
If the user clicks on the See Details tag the cards will automatically scroll to the correspondent card.
=> Adding anchor

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_my_mopeds.scss, app/controllers/mopeds_controller.rb, app/views/mopeds/my_mopeds.html.erb
Worked on front end of my bookings and my mopeds
=> Front end my mopeds

app/controllers/mopeds_controller.rb, app/views/mopeds/show.html.erb
=> show page updated

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_show.scss, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
I changed the footer and the boxes to fill in information
=> style changes
